# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: default
stringData:
  SMTP_USERNAME: ENC[AES256_GCM,data:5TqrHAu/mx3MEi7m4+Pgf3HoRHI=,iv:uKaNOIcLTOxKbp3In7brEzhK4SlsCVIMxTz3+fWGXzA=,tag:SvSQLm//bpkOHDa+asTTxA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:Wxs1SY8wuoXD75a00WsU0A==,iv:sf+QBfcTm9LSNyD9B05VDpweFYFvepHyVzY8ulR3oKQ=,tag:gB6XTIFUPixnS1uCsvygwQ==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:E+OO3SKZZLLuU1ce4OqbKxKuNyoUiBRAanQecdGdiuVnlelwEJbTLXTQWRIFc019ZzYOnFAjC/K9lNWYVHNkNg==,iv:G4Rjfett7t20Y4oqGZwauf4iXayww6WEqGRNWIEqGlQ=,tag:EcsinSGBHFZpqnRtp+QBLg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMHNtN1JkMmpUQlFnN3E3
        d3dYbGk3ZU1tcldRUWYrUzJreW44akk1LzFzCm15M0VpQzlXTVNKTHo1aXV4a2NL
        MFZzeDFCd2F4dklrMHZWT3V0eldhNmcKLS0tIDJCMjN2TzZWLzRsU0dybDF2b3Qw
        OGRhMGdMNXJRK210cXZWZ0Z6anhabGMKS0SodJZx/Yx5tR/qnTDjARTBg90kFY+W
        gdgrC3nUwXYIdD1u5RgMwpEGlnuE3T/Ff9JIRIOgTLgBUUMU+YyaTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T04:05:05Z"
  mac: ENC[AES256_GCM,data:19RmECwQHoZFh2P86/KnlW7lXzhU+3NSuqO3qjZ0KsOANyl7xIi5mABHkL0EwsZKYTr4ugTTsMl1JB4kqq6g5d60RLGpSk34xrf1EheFjEV1ObpQVv39ILBLD5kLuSMmPrDGGT2TlFdeKN+7Wa2FQ/96M9743r1Par/FBajkVEk=,iv:ZfT+s82fGc/vguMQwrRQd2vgGpJVEMjvtCRPx3hCrvg=,tag:W6YKzFAt0MdQbOcNZcgYVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
