# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: default
stringData:
  SMTP_USERNAME: ENC[AES256_GCM,data:/mdWkmvjqhyYd0rk7Kvhso8VqXo=,iv:K9575OFu8esZdLrNF9hV6tLbC1FgksCDdQnWiJVl738=,tag:Y1Xlwpit6ne9LMFs0elXFA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:AEyxyf8FAcn39T4zK9ub4g==,iv:PjQeDLzQYHkpCkVGNjDwjHpfY/Iz6kaYQU2SGTDQA04=,tag:TriSZgMLS2dUhNaXLLwK7Q==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:2uy874Ty7oPnA0B+7wP+mEd2EbgDqQ7C0zHTgiXJyd0s4ujlKjxXCxc++GtRYqEN4zg0dyPk7bH7p/WAy7zmZQ==,iv:Mgin6WNQoGT0Vs2Bf9QBjE5hUNAN5ealFpTQM1bpwFw=,tag:3cywAFdB1keBcoSQO76YFg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVjVYVHVQVDd5UXVUTzNL
        VkNzTGkwdjVHUHg1bEoxM3YxSk56SUgwZXdnCnlVL0d6bDJ6MEFaU01ZaEdOcVJj
        TEZ1dVU4Njl0MFVQUjAzbmE2bWZpZTQKLS0tIEN6eC9PM2hFSGtwMjNwZ2x6S1JZ
        dVg2OHVQdjJndytONWptcExDS2theGsKW1HcbU/aNYVaVF79uHcfVLQi9CmZ72vN
        /SS3j+6XjqIh6dWQelBtafJYb5MD6hLXR4MObZC5ZaPd/gt+PZKung==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-26T23:11:57Z"
  mac: ENC[AES256_GCM,data:WEH3mepzHZvwE1Ffcj2uekQTD70wREUJIiBi5k9l0E52NMs7oyxZzaA+BRzSmJyX0XmLdlFVcTYTwUuu/Q8ze1iSyXfeGTkZ7UkIa54JtHkNGSXy5OYwGfns9GQcE3RVdC/f3BVJtG/3phPthMO0465z5WuacNI+DQCeEA0RSp4=,iv:lBdSXf93gaxTtfndt9YGsdR+0lkmaXBr0td+M0J3l+c=,tag:PT/tCNoqrVmezbnBDuvpHw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
