# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:TZNOQ62I0VlPdVj9b7qBj4+NCunvYEMHI7R7HjlMA/2KmcXO,iv:cyR3QsKDnaDaywrpL91hKKUAxOsDrDwI+XsD4mhe4q8=,tag:QbKCzm+kdtCm+xxlmWpBMQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:7p7tXRFt9WEC7M4ZG0cFo/oJ+KVa4Ydj362X5Y08b6FFLHnY1AEmIPaW0vGEG+nHGORWJ8WkNYoiiN3sZWWeEe2BPqH6Ucf7j92Y9z9u6gDe/yC9+hEfoqKwd9iItN8W9b8wsVY/sFtgu6fnUISUYmOWkxCyhMVXbMmVNDt5I3tDFV/lq9ZeU8LdXEXre0YvjSVuH/SXdITE10OIHJUBz/hYDYT+0d8+OL5scFtOqQ==,iv:fxnsrGHnT4T1juzVoj02VbHH33ZNQfOEgr1048dMdNs=,tag:S9AUYtAweKeU04VEUsT7Dg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUVNOQ2Rzb2s3ajlwVzhv
        dVhqUGtjUHQwclhxR2xwVEN4bnJIOXkrcWpBCnhSQ1JiWEZ4N2VMNWkzRjdERTF0
        WDRaZHN6Z2lmaExhSXF6MWdlUEFkSlkKLS0tIGkyaFBKK0tvK29vRjgrY3dlZ0Nh
        dDhvVWI4dFQ4aU84VG16VXRFVTdQSVUKw/8/SEe9p0fvVbQxiROX1sWLzjWtC1JH
        NhI23l6RKzb3intcEp37UuuhRGJUtFVbsGH+zjwrYHjWcg9pHnE0bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:31Z"
  mac: ENC[AES256_GCM,data:bbH99mtvIvN/VUKuIH3Ev96KjK8tQLLuc2014D6GDyYwRwAPSi2ZY9fpGiCJ5PuST2fWAB+qWkzjcUce9tKDljqxJakf2w47zmszwzDl+diZ8TbDWQHnF2vWQAwyDAShhtByIP0l7tMFjuCUSJibyKLaj9aI/m2rAk1RVS5Uhvw=,iv:DzjwgCgGnfXZcWnnMSdipuptxfi89BXHzRyQRlCjLOk=,tag:KTrLTqGAunXVWblcHBsTUA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
