# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:afeWvjjVZiMcV8pQhjy/mAAK98my++9JgJKU2Zv71pxw2resOJpfIrkHYgpXnjainmRHrtOxBCqaEVLaqa0Cp97CGVdPgBhsEV86n6UFFLwVKCA7T69LQpNF1/A/GIMpAoSY+K+MI6JS+pLLFd5Vkh07KzKclUqvTlaUR7mVuJoKTZYKJ5Rjruwz66vwjmEZ+uOP14cGn/tYniE/dp8hH66aRoR+/q+aA/mWJdGwgoinJL1Q7Q==,iv:wt0h8f2CktJPyUC1/BAPS4URVQlDuP+MGA4Ur0Oj3As=,tag:Bwz6EYWiaCfjh7U3gohM9g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w58lmpj3jjxewn5w4hu6u44zyg4hstq3vhwmlkmt0nkp3h2rm3ls0pyng5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY3R6WEhRSWNSeGhIbGZT
        a1QvVlNnbXkxaFI5MTVaQVlZQTZuRXBoNmlnCk1QUFZLdU05aFlKTWdaM3Q3Q0hD
        ajF2dnlJT2JpaVhGdWpnMktFRVFhTXMKLS0tIDVLbU1LaEhzVTFKZzRjRDI3Y1Jn
        YW1ha2trN1VIemVPaTFJWUw4OUE1eEEKBkTtixP/AQWjqh37gP5Z7UAFvLkzO/fm
        o9Yde/nwuZzI2A2GBORSk+6NbEVbDXc/zzAFC15IL2owfROu/DD0zQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T01:22:52Z"
  mac: ENC[AES256_GCM,data:oKk0ZuQywUNPKlRs1nKPjqLaLgSMGOHkp7LBnw/udNd1pA7IAy0bzxv4zCh0GEJCHvJCPa2S/HdTVvB1cE69CTBl21Yu7KMraFYFcySe7QCOG5J9ir97Dc8HTf4JjNJu82cunKfkpadbGwqkbuo2lEVBOU+fgy7zhiCnKFItHcU=,iv:nkVuMsNoWW/XSP1RkHPyh382TCq+WDXCQqNZ7XGS+bo=,tag:1QaikwdTCtDg3Nohq5kDDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
