# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:3ztF3sRFbe0ZPk9Z9xvi2+HTgTUu5nL47H6RcHd2DvJjSEu5,iv:onjg2oRxWJN11bL+hM9IecIlC+B2K7+h5aTbmRIIOEY=,tag:7aiPveryqy9i0sis1MxL8g==,type:str]
  credentials.json: ENC[AES256_GCM,data:+382FT5s6gwmZicSEZVWkf9gSwyou9D8uSuR8Mf3F98y7lJEzQ0/Yb0fnhtnahoQKYrBJ2hygZAKLUdYyWIkpFB5AdSqe0G4f1QloBh4aLX/qU0aR12m3MUzVMXFN5UcT9WpRpV/6S3lqVqrgKecXTiCK+AZ9ZihUCfpGVB6qorp1byxrD0D8z6pw021spwkBFhq/pERZ2QGGzymchivOHG3HUGfqPQgmPtBEMecAQ==,iv:G2jydMSJmCnocEhjGUeJpbyzCvt5sT8FTky9LDvJPac=,tag:BFbwCzK+M2RLNRJCCjkjeQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b2lENi9XcDBmenVkai8x
        b1BzN2Zpc3ZDNWIyck14SVhhd1oyMVFmV2hBCjdNV21xUjlnWkNYWERQUlhKb2JU
        TkVkKzNPbk10M1N6VE1iSzhEcTFFWFEKLS0tIHhFbFBmb2NOSG5lclFwOUxzNDMr
        ZzRYTk42aTJmdC9ZTnVzZy8wbzByS1UKgdbj3fRoZbXrK4Rv8r3UW880/LANA+bN
        w5YHG01SUUy5uBl7ZLyZ4/4cA8DTib2XUe0w0PGY41cgqR5RpNNW+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:29Z"
  mac: ENC[AES256_GCM,data:3bhoWcQikoQPtP1ywMbiFzFpjYn02zdNlM0uWcYt1SvsZ5G++c6Qwzcm35Aeb1ooIwrWs0E5Zxzeb0/PGNibag+0YvB14Or7hmQkytF31eEqUtK8/pSfgNIw/O71y8z8aanOLh4hxBYdmIvAKzD3bxDnZsQn16+RLh9bw3EFtx4=,iv:2KXZlNREMBANI/dDPj+5fGNxk4cEethHm70QUkgRH8s=,tag:draQVI7X/V5qQczWi7IFoQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
