# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:xWjKJkR91sHOYvlhKqoyB+AxkcGmMrzvrVSO4NqES7C7teft,iv:BbmDfkOcO5PdYygIT2zAzvgTiprlsBIHOPYHo7xXCzo=,tag:x+GZk1+RsVWe9+zoFJu9Pw==,type:str]
  credentials.json: ENC[AES256_GCM,data:u+agzytTALEsONLuWukppwdiQ1lIGQBUhDYK4cMfTeY8S/dO57qSnizOAM6Y5vyyrv9yGx8bPK8J5tTL57bnSfsShh3Oy87F7aXTunyE8NWiMziCSV0R3WagaKX9bmAMVnX47sJbH+5Rmc14bZObNbF82g5Ph/4RhPNm6b44qEJ5f7jwUn0cao5HiCdiy537zCcxcX8UJthAMeq3goO+OPLLziiDPmUZlYjt/Ba8FQ==,iv:uWE07iR+0PCIz9EdiVR3dFsGbsbjsaiCORCFZ6R/Exo=,tag:xJ2ZVfHQNDa5jhHCPx8Hzw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2d3OFNxMmoweXJnaEpJ
        ZUl1bVAwS056SjdxZlhTV2FxaktLQkhZUUU4CkN3L1FoWjBiZHlDQ0oyR2dkY3Vp
        eG9uMDY2Y28vM3ZyRHEvbE5tUUYzekkKLS0tIHV2c3B4TWE0UHVLRHFSVWxHYTZK
        RUI5R09RaXJJVmpSbWdtS2ZiNzFLeXMKW+bAWwt2hyDseTF1WjMYcdQetKYrkVzr
        fnSzXD3TaSIA/TYPylkzcrQcCQ0OCLKankUZqleFuzQF+wqakx1cVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:13Z"
  mac: ENC[AES256_GCM,data:o0vcHYX9lEkf09HjI152h70+xqawyZEywI2oHVwZfaR5VQRlkBiEfF3pxpn7VDagOBx9QKm8s16SjaCkP8Ds2YV33uaJw7tlu3+htbv2zECQwVVI+DeOrkkju2j1Yn0/cNTrbqrAn1z0R51LqQvNK5clfd6MM/0F0kw4bupLiso=,iv:9dA4ueSDWqyeXSZLKIwvl8tMsGnsLGU7xdWka3OGTZs=,tag:TONagPCc84Q13nSQHHaMiw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
