# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:f4VC6RbmErinaZ89tz2BhZDr90WHFNwqfTsgYjiS5j4=,iv:mmOegYhpyE/4niKfWXNV8RfBrI4UuV/Z+y2KMoJ9mWE=,tag:JBBSpTQYCUGOS8og86BOGQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTzJhZ1BtVTNiU1NTblZv
        SGdYREx5VENtMHk5QktxWVJJZ3FqdzZlYm1vCkE5UmxlRUh0WU1IU3lQeEw2SW1M
        WldCYWtlVHVKYmpNalZKaHd2THNmSVEKLS0tIGhEanNvM2pBRndvd0ZQekJBbHJ1
        N2FqOHpzWWg5Tm5DWGlGTTlhTnVnaVUK2tC0t/l41LyH0FSlKBJa3i9kKx3HAGI0
        EeWWURorcZnahQiu79PBFwbvSzqEXQqvLzHv9sL4EgjqvalIpL7xrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:31Z"
  mac: ENC[AES256_GCM,data:6m/GHFAp27XN4UeHwHRaflaT+VZP6lgihgBzDsPJCJUIVyCpGMgbHQAVcAi5YWCO7Wh0s3mdSFo4pBHBD6qmJoGr09OxZqzncdzzVnAHlmCmI6i+HCafPrbn11chZl1Qo86s6USiuM0Xb7ix+9nIfSgkVxTW6mRQU1CmHef7c3A=,iv:aFObKEKQcWdLimzjKW1oywbo+3Ww6ccmKMMmDa/o85E=,tag:80bF8UGBdeNTmbp4D1NPtg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
