# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wvnZ/KyOe2jE+eVuXNTQnL9sFz2ZBdmkuMk7ibbKvb8=,iv:LiNm+JuaSNx76OnN/GUjwoHOUGjm0unxZQI3YgBykhE=,tag:Px4QPh1VXkNKop5IniRnRQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNEhQQUdoVkxVU1A0WnJ3
        bUlmcDI4NzFNUmdWRlVjN21KcDZnUnRuVFdvCjVINzIzU044UTRIeHVvUTFUT3Fp
        OEZsU1d6QVJ4bEt0b2xHTFBjcHh6MmMKLS0tIGNQblNZVG0ramp3dGtzUmlxbnQ1
        TndzdG5HMzVHNVVFREd5WEpOL013czgKD7u5VODj7N2Yvkf2r1ycBFpIJhw48vL2
        /nnWlqz9Atdqt+ithHKo71U36aXpZ+gQQKCNcSHfocIZbLs6GMaXcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:13Z"
  mac: ENC[AES256_GCM,data:dQGDZq8UjTc6ii1W8ZpQ6ftwyDTBWh+dOU0EdfayW5mFJAffV6ePhsp6T2DiWaIZ3/bu+NPDiz1kvWFO6dWQSf8ta8bzkCUcjYgSzl6p9SLpdcjddwdA34lEPQLgJ0e4LfI4ZlDyq8liNWg2ubkk97Y4OtAb70nRlgh1pFDQbR4=,iv:e8XSij4QbkvqBM2qEITtqk8dXMhgXj0c+Yzl9GcwJEg=,tag:9Oym3VlmVU1kWKe0di2lvQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
