# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:iA9MkafO4QYO7y1feeXUGrc/vlXQK0AGkKn7UdSOHJc=,iv:h1zG3COScDTg7JbtcLDMXGZicjeaeiGDipWmqj4ZHCI=,tag:kdoZ5GP1uGIXm/6R/52rqQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbnVSaVd5cEEzVDU3SjFJ
        VkVYT0FaRG13RFRPZVoxSXZpeFVkS1pMVGdnCmwzbE9TTlVZUzZsQUh0UXlxZmFF
        Vk85MHJQdG1OZE5xakl6MGp4WmJJak0KLS0tIEdhY2hkNjFFMDFoSFJ3S3ExRGgy
        YmhPSGVaVUkxNkFYekFhbjA4ZFAzNHcKys0bWt3oSjWMSMi5ryyYBpBm9rQbFbmu
        dQw+6E0Wobt7GdIm+m5hDVFZA4bMEuxbvJjs6EGXbgY4BxBrkP7qnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:28Z"
  mac: ENC[AES256_GCM,data:2ipmvKf1iX7KN6BsEzoGDDaZUbQek2cP/Z4XiqPDaTqDWzA2bPkqWvLKkMElCsGpAEjkWhhDkcvtIW+ah1i/JSH6tmDy0ABpUY5c+tcjd7YVSSHH1ukOOY3hdhdO0wjdwK5/JomrSJu/gXwtLw423PTuVrHbtDUYKLvuqRAp85U=,iv:mqYrD8gVSLfC1T9g9sT7TgXiFoyCV0/fi7ObGfW8ZGA=,tag:NzekCDOC/U0oFFcXuE3P+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
