---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
components:
  - ../../components/common
  - ../../components/repos/app-template
resources:
  - ./rook-ceph/ks.yaml
# transformers:
#   - |-
#     apiVersion: builtin
#     kind: NamespaceTransformer
#     metadata:
#       name: not-used
#       namespace: rook-ceph
#     unsetOnly: true

