# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dgHO2txmd3FtHxrmdPdjXOLRYD/HT3ZXhFIQE46R5Q4EbrWpIe92MA==,iv:hpoFDf0N9/DZnMZkIwixXyLaufjWom4xrSkupo7GBqk=,tag:3ceqadEUA/dPI7Oj2DdXGw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w58lmpj3jjxewn5w4hu6u44zyg4hstq3vhwmlkmt0nkp3h2rm3ls0pyng5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAremdEQ2hrcWtLd3R5U3BF
        RURHRWhkY25LU09Sa0U2eUd6cFZPMlp6Q3pRCjZlZXFTbXNoOVg3Ky9QWnRMTGdk
        Skk4SElpRmR3cHhYWjdMK3lidThtRjAKLS0tIGJIVC82RVIzZWRKbFVUY0I5azVE
        amFGUGhSbXdrZXNjekNHcGNpeldEbTAKyinYLxEzmPhu/nq2qVtVdtL+EWOAdiw6
        SiADVJlhAjrgdJS5t8/P5p3bGtd1KKDJkwon2QqcZAFkPObf1vvLpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T16:27:41Z"
  mac: ENC[AES256_GCM,data:tpc3aWm2OQ4rJXL/pg6RnzL9/wDDOGQ8dwAhE0Mg8gLWybragGbgQ75h67hipz4dQydKFkt9CySvX+hC3ckB+ueHvZHCfknx8Ypv+Ni0HyQr03WMdamDOSj1ZkGreAtpdWS9vwVHqCujJkqiBhtfNvYexiDuuY1OJeA1zPwS+Eo=,iv:BDLFMbTxMVm2jXMShZRhrXRq8veKJF0srO91Ai+49zw=,tag:HGcWJyOjI/Kv3oLkKu9zAw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
