# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Y2Go1gEKfdK1q+Nz+g2Ijsm1sWSvECS7SPgYyWZshUFaoL66rN+F4w==,iv:A4BX8AipyDE7w1defcPAMMqcV3/Ez86hffhuLWSfYD4=,tag:GrOGdfTMnGHsiZ6PT5JO7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1cxZndTY3N2NUxvam93
        amE1dEZDZVcrOTZSOXVOcUFzL2RTWEhKdTJzCjNRS09YS3lEcTc5dGM2L20yR28x
        ZWM2ZENlMStUVFhVQTExbCtoampqeWsKLS0tIHpZQkRDaGFINmljZ0ZIRFlpeXFm
        RkxqNkw1TGRuOUlPU0hpSjhOSjFnTjAKm1x428qlT118Ode1GZ5iQujPClHFXNQA
        7IBaATNy5ZZtvIaTfwrwRj/H3KTlBgYIKrbnrjV0q2SZXzQJo+GdSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:29Z"
  mac: ENC[AES256_GCM,data:tKVLkBqXu05BmPsxkrUYR/OMUTXyRz7Q5CYI/oY3npTslE8iflSlXnUMLW2N+25oGMbDcuktSvOfpXoQVi1UlEVkTdoUUAqdfdtBtHpZc42yphX46GUZLMcYbER/XAUC/o5YIQyFYOC9T82nllRXbBs/6Zn37Jded5oII1bVxqk=,iv:Ao+KmI0n9XWfyidiyX776B5byhEwvydklZadPpUcR7E=,tag:Xf+3lVPHIO2n1o5AS74ucQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
