# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:nIkJMBSBEJcZVvHSwUDsge7TK1zcv4FE3+qH3/OHNicog0DVNpO93g==,iv:ZXbjMo+j3vfr9D9Ux56j2oCtOusmZJQ73HnXoVIlciI=,tag:Ev7AXwTD22hxlgGgLFv9Zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU2ExT3M2NVpLM2lTK3Bq
        R21iYy9mUGk2Yit0Vyt1UVJVaEJWekVwaWxBCjhaM3Y0RkhFcFRBNGxrUkcrY2JF
        aGtOYitIOUVPTzI1Q3Q2RFVoTVVBVmMKLS0tIDRSL1NnNWNGa0thRzdXZkxqTHRT
        U0xBVmtkcEFyV0VlNWd2dVBWMXYySk0K1jcp3XYGrhmpuyEcKFEJgHLcAs+je3CU
        6oPJtPqDN1LwWoMRuViOeioaVna/hi+NOoH8WWn4JnJAZVOEhu1Dcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:13Z"
  mac: ENC[AES256_GCM,data:+mvuBb9/COayAyLMp2G9N9LMkPxnBZhllpjdrw6GwVhLvwkAUKAoMC0I3mz5T2jfWlOMKBok9UkDWKPosnH31kUgXqxEoN9WPygMJ6kTdwMINUXGogSbdZGgbuKwAP9rpf8aZZCTR5f9wx/udliGTxchKqniX11XNc3CVidemGc=,iv:RQauBuTvJKtG5IyZJbXZfgi55YnqMulCLKNNa+R/t/4=,tag:97sU8fq4rjNxJg9bqo1BlQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
