# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dLI4dGqCOHGfIRa2CmB2BMwfpuvcBXCF+a4Vhegy4Xs9gBRALkJkHA==,iv:a5Nk8VI6/dyvufPFRsJgYccRUPQn+7qcOhoqgfT7zzI=,tag:w/M9FSZHcMsbXEysfJDW/w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MkZRUUdQKzdPMXlBWjAy
        bzJMb2dUeUtpZFRhWWhBbFQ1aDY0UlB6NFJFCnBnTm80MkpuL3hiM3VWQVZCSVg4
        YWE5TkJXOVZMREdKVGtLWDJ3cVlnZ1EKLS0tIHd2QUZmRzE4NjFQVnZqeW45azRX
        STdtZTNBbVNNQUFockpIWkFkMW5WVUEKfK2vpiUcnjTAlv99dKlqsfzPlgIc0lxX
        8HmL6MlXoU8OnWP9afFHrMFJ2Wm56BwwzbTXRkK7zpp3Ws8PCX27lQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:31Z"
  mac: ENC[AES256_GCM,data:duTFkFufpIInFk9PiwlQUgfwuFbRw5m8569xHHUNbx1mm/tT+2gPr+fbsAbMD1eHmyztj5U9S26MgvN0F/xcXUc/8DXfbtwetnlHsHFUF8m5cEr+ObG84ovN6un6Wyh21JDZkkaZ/2ywEQCQjjS6P8tid7PYd5vE6mQQNYlqCWM=,iv:77iFNDMrnytlpV4jgD7qAak7k07lZuaOC9cvEiukSWk=,tag:4MjERzqncPq/NZWShymqfg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
