# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yXumb7QsQiXMAiRg2lmIyyViZLL5b9bkFrCeHyRRdM0=,iv:w9lO06nHIdcH2y9V54BBhTC7G97Jtq64Q8W6S6jWmgo=,tag:AwW6fgGUh7SuXAEBJwgi1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w58lmpj3jjxewn5w4hu6u44zyg4hstq3vhwmlkmt0nkp3h2rm3ls0pyng5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdEdkVktyVHN6Z3FlNEM5
        Z1UwMmRub1BSVnlhdXdJMXc3M1pRTnZBZjJZCk1tWEd2MFNhUnN4dVowUWora1M1
        WHhxaXJUbDk3cElkajd3QmRuLy9JRjAKLS0tIEZQcEtXSHV2andQdDVMVWxwN214
        cDRoSTAwT0c3c0UyRjVqeU9QaG5XV2sKiyRyZPpTlpr75tp81/ELsj9UkZfXGcPt
        dpUHON4qmGVugPf77sZWf6uEAlyrAodwfs7oV63JrBfvzQmy0CtM1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T18:20:59Z"
  mac: ENC[AES256_GCM,data:DAVXyQhK2akVI36GgXOt1gi+rSutnepcdYuYE3qzG3mr/h5Ah20eVAc18puHMkLkhxlgEIyej67xDBGED9pa6aGZXnAMTCo7ZU/UBfiFOpaOpYIeC4mpm03jri8nuvpkj0Sapijy8YzBk5dD1zHzAHCxqc3EUknrNH8jeBs8rjE=,iv:OptGq6YlWurJ3wAl/57MkAWU2l1mFnaBNzRF0CWdusY=,tag:95HEgf1OrLreF2bS8Vdaog==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
