# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:h9wlIHD/rW9pdOUXr04WYbuNR62Tx7VgsbXysQK/lYBiLy8ZS+dacg==,iv:itcsGSeTayfFxj4tIhxitfzlkQILUV2NLVjYvEqiQFc=,tag:iTkTs4sS+Un9U7IIHQvTxA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeFdrcW0xMGxMN3hrQ24z
        Yy8wVjFJMHF4MTdDa3pCdjNLazc2ZnNkOFFjClJVcForNkJsN2YxSTd2WURxbkUy
        SGhXN3BuNmViNlRwbFhBbDJpeStqMmcKLS0tIGl0U2UwZEtpdkM2MThSTVhNK2lT
        RnRoNmxKcTZ4UHkrbS9sRC81SlBQekEKpl6kQU4qhD31ohh7UGRKGjOir8bUCtwk
        Pn3O2kjyYl3QpwSanmXmoqj7LWHM2HvUIrYS9hscDlnhHqjSPmHwFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:29Z"
  mac: ENC[AES256_GCM,data:udysXAG5OmrnWAlwmAI9rPLVjT+CevwvntfXGeyMCHVyirLGr90PzgcQnUfjQk8ceAjAy7KDFlnO4/bJhvl/nePAr6omi4glUclS5u4fxTBL0RPNORiBTC0OpaUlNB/2TdQ6wAiSjjzlw2zIXVGUWAulwJg9IzkhFFLTq4vMzek=,iv:q6hqktQObblGtOCpssKRXKQibIF3QjWDKAcoGurgjxg=,tag:wnSuBhzzKeNklZ0OeiGC1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
