# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KaU1uHTyaW/scCTT68U9RtN8ArmVHIvJTR4a0a4Kzzwsi+3g+GfRBw==,iv:P0qpFh2X4OsDvh3Oz5KE7jyEUgEejt0OFhY8IhuTsRA=,tag:1f+G46w4oXxQVoahzQQAhg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ1BrQ2VJTis0MjdUYzk3
        d1EzUHJCSEkrSytGcnFtWUNyeU5EYm90YmtzCkdHVk00K0Rta281TmFtTXk1U1hH
        Z2IxaEs3aVZCdXlZY0xGM3hDSnhEaGsKLS0tIEtaeW5XMGNUWksyZWE5WEQyVWVG
        S1hQTWZwd3RFVmVOd1Y4VHZ5ZDc3TFEKeX9WNRIvh343mXmz9JMVP1YL1Q+cZOwD
        d9ogM0T0jbU/D1ulFyZcIaDyl0SfCxMqQZB4jG2gVbAPXVo7GKQBGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:14Z"
  mac: ENC[AES256_GCM,data:BZp63z1fwyf/LrHT+XaUl7K+fJUMPQTZ7KCWm65+r6squtZlE/ar87122dNuwkhetvzZFdjBu5flfMb5+RLVJIBVLvY5yStfJoTL73RFHKObDwBRSShQ9vmfiXSgQePOf+BVWjjIUc8gUUmcXawmlMFcdPMOwf+apYOCRAM7y/s=,iv:pPyK8fGJ5Hvpcl566wy65UTZtgouDPvd/pStrGQBZ0w=,tag:KzvOh3KR80jKuoVGuAb9Mw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
