# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:tsxmDxhLYZ2A10oO7aBPMQmTOJSyfTk6a/ZWaC+DMNIxdwx3qzpDwQ==,iv:l7FbOzQ9/fSksWYV28r7BQdtfQJWBuAYVU7fv3OQOo8=,tag:9DOlUePQhuLYjP8wfgqtdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSktJSFlkdEVxZjN1SkRp
        bS9YcWdHemhiWFNTRWVzV2h2enFyelc1V2xFCkYxVlZtVFBLNklKTjBHWC9BanQx
        cndIS3Y5TDVKam1yZFJDQ3BVVHNwS3cKLS0tIDBFeWxMOFJjakM0MGpvcW9kazk4
        WlRkQ3JKQURubVluVUtKcy9pKzhPSDgK16o1VmkQQWQWzEn1VdzvWZAEpy5YHwxs
        otfYu0sUOlUSj08SwOXH8JYC2oD/hEypGxXD1g7OGwZor/4xvgCalA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:32Z"
  mac: ENC[AES256_GCM,data:jBM/8VwJSJUWJCzDMlgs3pwM68L+BBa+DHqQqjLb2PndUym6Cv+mor0XL9ZYV44nii1WQrZ3Yfv4eSCdd4zCgJ2DxBsYed+rXZMQ2IlorYEu7DCYhuul7t9Qmvg8xsToU0KHvFI40MJHLqBNHRzN0IYOi0YGMRpZF6ZNtTXs8DY=,iv:sOCRpxIQOi7aTSxQ4uW8dAfIghvinswC1366Dy/LSaE=,tag:nIcS9nX+CWLo2esfv4eUGQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
