apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:8zR8CsFwoc4f1aYGeK4=,iv:JMqkgEFn+yTgkfWuL0VNjzqmppFbYjeHHr9el7Y9ELU=,tag:E0iqzCG9ph7XUPv8ZAXBHQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:YirhVwhw0DmUR09/5scNtToaHq2KGXaWI13BuT+HU8aiSVQi,iv:dgi6tzGDzidwE0tBOxp88q2C16LTqvL4dzW/Nd1+8aA=,tag:DRCCnaAjrWU16eac62qzOQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlazcwc00yOHJvV0FJK3RE
        VzNuaGJDd2cvMEIySVhyQ1lmN3I2NXIrWkJ3ClZwNnZ0aWJmWHBxNWxwdkVVaUdU
        SDdiRWNsa3NuMkNHcEs3Q3lpdVhveTgKLS0tIGdqMUNIbjlNSkxxNzRaWHVDT2ZR
        OEljY1JKdGdBdkdYMlZnMFJlVXNvb1UKGQXuE+QC+QLU1Jv3g/BSlMo3KHTzsQCz
        DlFPGec6tPUJ3nd2N+RsOsUHftgu5Q0WOa/E57kNWka9csGxdV7YhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:31Z"
  mac: ENC[AES256_GCM,data:0nXSiGC5UraKfYv6L5bCdMzPIPQ8KCZyR5sFln/nkOk+z0uwnjEBlBaDaDTK5Dvwwg6kYeleY+RDaGJi8VqBdVTIkroVkXpooLpcjMMs6sPhMZ6Nx0MOU9H7A8FRHvX3PD+9JHltZ7koY+mge9HjdjJkcRyAOa0GycsCbMWDgBU=,iv:SxTtSNVQk1I2gGCeMyQ8TXt9ECfDZjTnQQXlxhnHjTE=,tag:q8Kg9aCPoKAKZTkBNB6mmw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
