apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KVeWnljisBmKtvce2ek=,iv:PbuHT7E4k9cIwmQYb2zgcenJnl88I36FEMJPp9ClFeA=,tag:YSIUDpBBIi4o4s1pWuoLTw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RGV46AP3ConB2vodiraQlTOEFxpkJfHwamsibP52PuYULx25,iv:uSwG8bI7GFz6pcfDJqe9u1NLx3H4QMKB+V0jyRl79NU=,tag:Xdc4Nt8DQpmMV0+Mj5z4XA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMDFLUzZoZnl2ajl6YU5T
        SzM2ekh1L2l6ZWc5Z29pb2YzeUhYTTNJaEFVCnR3QWdxOUhxYXpaWFhWTitueU9O
        dEVITXlkM3R0eVZ4bTljMkNiRUFyWFUKLS0tIFJVaVNOMjR2bDhIZDdLRi9MR2tO
        eEVTK0JaVGNUQzluVUwvK0N3Z1cxbXcKUPChsuHpG76Q6jrnFCPXCPAsq0Jd1Aeu
        YUAcxI9Pf5/Pn6GtgsF9IiJgMaDQXhh5tIC+RCal5FtEcegsL9u0FQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:28Z"
  mac: ENC[AES256_GCM,data:T0SGuT4QDwQlJZWJVQ1zQciXxi/+9GB5bClYwRErjNyiL+xSOzuDroDeWoZJFfxfWqBVOvu2AnCsPwR7xvrwFkjbTWnrzb1llC9asKoQLsj6r6K3XiWqmzj2XZX1FfEHkP3aqI9LFp1itMkdjTlgnt9j3HsL0bzjpvbDEqSKQ28=,iv:6VZBqpwaLfSMKxxpL53FiioBqja13x3UdpraIpqHRkI=,tag:s1RGsdvpRLgHAyutYtjbpg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
