apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:OUQhgNEEvbj4l7V4Sk0=,iv:A6zOwjgGssEd85ypSo5zieIXmb4szgfMZvs5JW5Rg+k=,tag:hKPELNWwVx/yCxSDOwNRJg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w58lmpj3jjxewn5w4hu6u44zyg4hstq3vhwmlkmt0nkp3h2rm3ls0pyng5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWhLT0RIYm50bkFzREJy
        eSt0N3FVdnRDVjVxdkh2bGUwLzJKeTF1eWxzCjc2Q1ZzNUZIUnQvSERTbXlBSkt6
        VVBtTWh1NzVnQWN1YUI0MHNtTERmRTAKLS0tIDNWbGNtY2dKanQ0eTlCaHhqZit3
        T1A0RXMybzlvSGR0Y3lmMjh1QkhZVVkK15Uh0PkFhBMLj5F3zV4UKdtas82fpdzZ
        ES+IE2Nej+FLJnFQha4stZYaRDvAPSRVjtu7vHhPUfdScSCCbZZA5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T01:25:25Z"
  mac: ENC[AES256_GCM,data:eHYdwqMg22+uH5jexhMaauP5aw5424LInBP8Vc8yKtFJ68CsRscsQ7IYJQGcwUGoiIh0iqDH11yBWOgD6gR4hRz7yZQaCiwCz7H+EVVGOvN12BgsIgTf9+8OfvGo9Dk/PEXamYO+cJJlw+wmD0nj1P5RTSXfPnzTY58Ujrz1jhI=,iv:pvCbg/H2UQRMNfDjtr8SIfNQoy3KabNqKeT4Z5/k66I=,tag:6xqkjJcFzDXyniIJiDTqVw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
