apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yN/IsTFIe1rr9c1/BoY=,iv:ZhAttLwg/7kf2fa112dd184jmn2NTQwkXXziO9Z4wnk=,tag:G2h0DE7fEjybJT7IeM+zsg==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9cDY0hh/Q15U/1Mn6ifi0hr4je57yQ6fxnmkbrcvs3Ikc1Ya,iv:+IHwDC8+t/qsBDx0BuRHhJwAlB5Jj7qvvwCFrgwkuMg=,tag:3vx7rPWwMN1bJ8KE2OfvvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa0hiczBmcmpkbS84a0Z0
        RVpQcmRLcytxaC92M1dkeDdGcHdvbEFEbWhzCm9TR3hSdnJYMDdZUXdqSFZyYTd6
        dEZOVi9qN0Z4bHp6MVRJdExDbjdaRjQKLS0tIFQxNUJNT2ViRGlzZnYrNG1mTGxB
        dUJ0Qkl5bzBTdVErbDluSzNNdDdOWmMK+mlIec9NMxFSQ4XZ0sXXCkzHEXwuXRls
        9jBHim0YJg5194UOwCw+/DMmY1qBeQuXP59tUDXPADHYBoWoDx76Jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:13Z"
  mac: ENC[AES256_GCM,data:Vtdxv3UB9dfkixlqXvcFkVGi2fb1/t0R/7cAWYxQxvxK1DyHqYMBR8p1LlLes7T3zNtBeUk0EIlzJMvAvNvehCJIQswsLYe/capOZTdAXXM6UtHHp5/e3dyXJdvWgdgEvvyO8F9tpmOj38I+RV8N1pFEG9FiaQf5ZqkTeDI841Y=,iv:zHeo9ilcVXPeVWtjBDMnfapyzlcA8G0bEExDqx6oH3k=,tag:IZoKlFcOHYE2SGoetEvbrw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
