apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:TY8RZeiEOJgEUQe2qvj5Q9Ju6P5nqdqkB/LX5fzKwIKt0AyNmqPzMORGNMKVmkh+rCp4HbBNx8tX+FrGtXxTciTriDCWW2axNCzx,iv:fG/INKdoLaxbeTaxCenS3IgJMA071OTEp6MUSQiu1Kw=,tag:oFlci/tSGlHInZ+t53W/Qg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdHFXT2FESFJIMjVHdWpk
        NXlIam1YT1Fhd3JkWDl3azlSTjNOckdrRGx3CkJaUHZ6OVczL09jbEZ5dXJQOWtC
        Vm1LbWZKRlhvaDYvYVVZMlZIM244bEEKLS0tIDBzTVZpVzh5T3dWMy9raENMVUph
        Mm45S0pkVGhYclVpOWhVRUU5MHYzMzgKCxkhCb8Gw92iLc8OyD4Ym4MGpT2uqtbj
        TCb10uW+aSImzjorPwyXnWWCpcWUyMFjseZjihXO2gbyfOnDkbzsGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T12:54:28Z"
  mac: ENC[AES256_GCM,data:1qsoHXiH/r6JD5NKfTczP8aZrb8O0OR5W2hQZB89BT3G4P6uGg9BnezJMrFkdgsEsKE3uy0zVX6EwPW2KJyWrOkbtwVpxaDzahs15JX5WmwPmpYmF4SDKzcnrkxTryUnW/qRGafIBxspC9F373GG+6TUnbJXdS+KQy2xDgCPIAw=,iv:4r+yXpJJmfZ6OY+ASla7rcYUtA3KKkh4y4/KMRTZCp0=,tag:CZ5Lk30OYwPpvPKY7m9XHw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
