apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:rlLwfPgu3/utWicDKdqRyQzk94XR3XpVDiIbG4keQsrwPROIzkXUtctXxxsCzkXTFYOOmO+xk612MHgY8zi9+qAHfTnwoSjBFMHQ,iv:JZmmnSM75zOsDP1ax2/3Dri/ZCY6rNU0TgL6QT58KVo=,tag:VcGQiElAztwHqpqDVpcaZQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRk9TdHZHVWlNWXE2dENN
        dFI3bnBkakxISGxqV3JnUWdMRTZuUTZlUDN3CktJVE9MK2VOTjUzcVlRY2cvVkdo
        Y2xKVUZOTitDTnFkMUdKNjBxTnlicHMKLS0tIGxqUTZnNEk1RlFYZW1HTk54Tno3
        dnFSTjdFRHdjM1F4d01sdDRjTCs2ZXcK584w285LyJWNn8wWLo+fXcIIBW/Rfu6S
        2ZPxhoaD6ByQ+sTQ4Yn7qfIcFHGxnC9Laz+zgxoRgE+nup5eV/F09w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:20:31Z"
  mac: ENC[AES256_GCM,data:EgbTwvCfmOZ7KGzY1XZuCRO0BH2iSME2w1awgNIy9pV9PmFbOCjo+bLXMY9CT6WFtGkKjsrklCxWpTWkSz/wnIGiTxXvQjxwEvtGsx4iibUUKrySwLfWxf9Fe3TntRBWLdvVkWXQHOhPlfV+kWuQKA4w8rMofpxNri815+H+ESY=,iv:InSM3rBbk6E1CkTWGdFPUpq+GFfj36gNI7DRz+eDw38=,tag:2PTzvGi4iL3fgU5SK/8paQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
