apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:dA8Xm3RAj1YM7lG/l2EOUNFqynUQ4numIyNDP6oGFzOBRiOPOiqWOyDSb9Xbhg5p1NBl+u7Mrq1bcxdSyFbEEOHE4vrHMRw+enjg,iv:t6QfgYvCvU6GOUAEs0iQmV8ijBHn/iH6+BziJPbmTOU=,tag:18EmawGvNWg0g8yc0P+XLg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1cdyas8xnauh38vj8adam43cguu88jw3z828n7ww470mttpq50fesagm56x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWkNkblE3ejVBalZDRXRY
        NklnK1VFVXViN1ZNSmwxNW1sT1JIYXhtN0U4CkVYVmRJZHAwT1VmRVRidUZFZElm
        M2F0OHJqa0dRMXNLQ2Y1WUpLaXNjeG8KLS0tIGFrSUROL0Z3Q295K1NXa0dVUmtz
        MElBUVZyNlZTMWJmRjVhRmpzSmtBdUkKnZEQCbpvH1SK7zZNmaO04QmfiVq4o21e
        MQSq6AFFromIaYPDrh2s0OD2nwNtbADMWh0yo9VhsLhhjPrvwE8d8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-21T03:19:13Z"
  mac: ENC[AES256_GCM,data:d/GKpQhpGNPVI9EfobN2p8yA5D9jUZLua/9QeeW0aWIn0+QVi/BrW2qPKbzYUm1NWKeKV3v+yXni5LLGz3Xt/Q2J/nwdzi5tXE38rJoH3kZ6EthrPPisZUeZ4ntcoELVZ/W6OoPAlU1mUrWHrb93ehqzgcXVicBR6+pF4VsRKBc=,iv:eDFvsOwDik3We2yevQbcigI3FDBiYnvstuRKQ7pE89Q=,tag:sytxAkUlvb0/hvtMDCll8w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
