# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Fgnx12GUQP0mYf78zvnQSJGKoJo4XA6M43V7y1H8GYiyI0YScr7Fwg==,iv:r8qyvFdM41mJGkU0jtY2G6euaUfbJQyxEwM2kIk8Jmc=,tag:DrHWRn05NlpxP3u9lpiq6Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w58lmpj3jjxewn5w4hu6u44zyg4hstq3vhwmlkmt0nkp3h2rm3ls0pyng5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacldYYkdESDdCcXBYU0pD
        YTgvTXg4Z2dyd3ROb2Z2a3U3NVlnblNqd0FJCjRGdVBQbStEaW1UTzRKUS9oWDRr
        T0ErZy8yaEtGOG53OTFjb2RXam11Z2sKLS0tIHEyejdxZ0Jwd3VQbm9yOWdQZ1Qr
        NmVIRk1BZkN0MjNUNHRGaGYwanBJZGcKSriTzzyK0A6V0RBAOWdlp2jTU1G1x7Rr
        fAAwEQiPkQSKeOrJZZbaERPBrUf39hPaKOSemPQlPCFInShGvRr5zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T19:05:10Z"
  mac: ENC[AES256_GCM,data:F7L78cvtMbRs0ok8QZIM1mwCI2F4k8vVVmW5sstKIf7dQvX9vRU4N62O7XBVABCORrL74TTN1n+D9aDywmFCiWksUp9OHZQ9wHBXhlAvkKIvSRNcd5QMsDNxy2aEROoDj1uxtd1/uqP0b+gwT/U+IsKjA+oE9k8G1edfpKWVRMs=,iv:xLXyHd2cvEmp8NdQixxHKSjyl8lZffWW5ef/mzZou64=,tag:MaR+6lPEno/A0OKmJPFJ2Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
