# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.216:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.216"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-node-0"
    ipAddress: "192.168.1.210"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:11:12:64"
        dhcp: false
        addresses:
          - "192.168.1.210/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.216"
  - hostname: "k8s-node-1"
    ipAddress: "192.168.1.211"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:16:d0:66"
        dhcp: false
        addresses:
          - "192.168.1.211/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.216"
  - hostname: "k8s-node-2"
    ipAddress: "192.168.1.212"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:16:d5:68"
        dhcp: false
        addresses:
          - "192.168.1.212/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.216"
  - hostname: "k8s-node-3"
    ipAddress: "192.168.1.213"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:11:14:4e"
        dhcp: false
        addresses:
          - "192.168.1.213/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.216"
  - hostname: "k8s-node-4"
    ipAddress: "192.168.1.214"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:16:c4:b2"
        dhcp: false
        addresses:
          - "192.168.1.214/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.216"
  - hostname: "k8s-node-5"
    ipAddress: "192.168.1.215"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "80:e8:2c:16:d3:3e"
        dhcp: false
        addresses:
          - "192.168.1.215/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

